//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hr_manager.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id_comment { get; set; }
        public int Creater_id { get; set; }
        public string Text { get; set; }
        public System.DateTime DateCreate { get; set; }
        public int Task_id { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
